### PR TITLE
Sdl2

### PR DESCRIPTION
**Pull request by kazzmir**
get things working with sdl2

### CODE REVIEW

**Comment by kazzmir** [comment]
compiles/links so far

**Comment by humbertodias** [comment]
Nice new feature! 
An idea about going entirely to SDL2. 
Would be possible to port paintown to webassembly and run it on a browser like this one https://wiki.libsdl.org/SDL2/README/emscripten

**Comment by kazzmir** [comment]
Yes my plan is to use SDL2 entirely, and remove the allegro4 and allegro5 backends. Work on this has been slow, but I hope to get back to it.

**Comment by kazzmir** [comment]
things are mostly working, but there are a few bugs here and there (notably lit bitmaps dont work, Filter* doesnt work)

**Pull request merged**
