### PR TITLE
release ubuntu (#72)

### PR DESCRIPTION
**Pull request by humbertodias**

### CODE REVIEW

**Comment by kazzmir** [comment]
Just so I follow, if we tag a release off of master like `git tag releases/4.0.0; git push --tags` then this github action will run, and upload a .AppImage file to the github releases section?

**Comment by humbertodias** [comment]
Yes and a file paintown-x86_64.AppImage will be generated

**Comment by kazzmir** [comment]
github warns about using upload-artifact@v2
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/upload-artifact@v2.
```

**Comment by kazzmir** [comment]
actually i think we are supposed to use v4

**Review by kazzmir — APPROVED** [review]

**Pull request merged**
